echo '// this file is generated by base.sh' > _base.scss
date +"// %D %T" >> _base.scss
echo " ">> _base.scss

echo "@import 'functions';" >> _base.scss
echo "@import 'root';" >> _base.scss

echo " ">> _base.scss
echo "// picked">> _base.scss
echo " ">> _base.scss
ls -1 component/* \
	| sed -e 's/\.scss$/";/' \
	| sed -e 's/^component\/_/@import "component\//' \
	>> '_base.scss'

ls -1 colors/* \
	| sed -e 's/\.scss$/";/' \
	| sed -e 's/^colors\/_/@import "colors\//' \
	>> '_base.scss'

ls -1 particles/* \
	| sed -e 's/\.scss$/";/' \
	| sed -e 's/^particles\/_/@import "particles\//' \
	>> '_base.scss'

ls -1 plugins/* \
	| sed -e 's/\.scss$/";/' \
	| sed -e 's/^plugins\/_/@import "plugins\//' \
	>> '_base.scss'

ls -1 utilities/* \
	| sed -e 's/\.scss$/";/' \
	| sed -e 's/^utilities\/_/@import "utilities\//' \
	>> '_base.scss'
