version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1602128313

layout:
  /header/: { }
  /navigation/: { }
  /main/: {  }
  /footer/: { } 
  /floats/:
    - system-messages
