echo '// this file is generated by base.sh' > _base.scss
date +"// %D %T" >> _base.scss
echo " ">> _base.scss
echo '@import "functions";' >> _base.scss
echo '@import "reset";' >> _base.scss

echo " ">> _base.scss
echo "// picked">> _base.scss
echo " ">> _base.scss
ls -1 component/* \
	| sed -e 's/\.scss$/";/' \
	| sed -e 's/^component\/_/@import "component\//' \
	>> '_base.scss'

ls -1 utilities/* \
	| sed -e 's/\.scss$/";/' \
	| sed -e 's/^utilities\/_/@import "utilities\//' \
	>> '_base.scss'
